FROM ubuntu:16.04
RUN apt-get update -y && \
  apt-get install -y \
  cron curl sudo git
RUN groupadd admin && \
  useradd -d /home/omnibus -U -s /bin/bash -m omnibus && \
  echo "omnibus ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/omnibus && \
  chmod 0440 /etc/sudoers.d/omnibus && \
  sed -i '/secure_path/d' /etc/sudoers && \
  sed -i 's/^Defaults\s*env_reset/Defaults !env_reset/' /etc/sudoers
COPY ./scripts/test_project.sh /home/omnibus/test_project.sh
RUN chown omnibus:omnibus /home/omnibus/test_project.sh
USER omnibus
ENV TOOLCHAIN_NAME omnibus-toolchain
ENV PROJECT_GIT_URL https://github.com/chef/omnibus-harmony.git
ENV PACKAGE_VERSION 0.0.0
ENV PROJECT_NAME harmony
ENV VERIFY_COMMAND ci/verify.sh
VOLUME /outputs
EXPOSE 9000
ENTRYPOINT ["/bin/sh", "-c", "/home/omnibus/test_project.sh"]